"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
from pathlib import Path
import dj_database_url  # 👈 ¡Instalar con pip install dj-database-url psycopg2-binary!

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y)_rp%7szy1elj87ts$@ui35oe&x@n#nqyk@yitp*-vls001gu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'propiedades'
]

MIDDLEWARE = [
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # 🌟 Recomendado para servir estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # 👈 🌟 Sumado para que las fotos de media carguen bien en HTML
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database - CONEXIÓN HÍBRIDA PREMIUM INTELIGENTE
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Si estás en tu PC usa SQLite por defecto, en la nube cambia a Postgres automáticamente
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# ==============================================================================
# 📂 CONFIGURACIÓN DE ARCHIVOS ESTÁTICOS Y MULTIMEDIA (CORREGIDA)
# ==============================================================================

STATIC_URL = 'static/'

# Esta carpeta se creará sola en la raíz al correr el comando collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Obliga a Django a indexar la carpeta static interna de tu app 'propiedades'
STATICFILES_DIRS = [
    BASE_DIR / 'propiedades' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ==============================================================================
# 🌟 CONFIGURACIÓN EXECUTIVE DJANGO JAZZMIN (GOLDEN STATE)
# ==============================================================================

JAZZMIN_SETTINGS = {
    "site_title": "Golden State Admin",
    "site_header": "Golden State",
    "site_brand": "Golden State Luxury",
    
    # Logos oficiales configurados por el usuario
    "site_logo": None,
    "login_logo": None, 
    
    "welcome_sign": "Panel administrador de Golden State",
    "copyright": "Golden State Luxury Real Estate LLC © 2026 - Arjona Blas",
    
    # Menú superior limpio
    "topmenu_links": [
        {"name": "Ver Sitio Web", "url": "propiedades:index", "new_window": True},
    ],
    
    "show_sidebar": True,
    "navigation_expanded": False, # 🌟 Cerramos el menú por defecto para que sea más limpio al entrar
    "sidebar_nav_child_indent": True, # 🌟 Le da una sangría elegante a los submodelos
    
    # Vinculación del CSS simplificado
    "custom_css": "propiedades/css/admin_customs.css",

    # Íconos premium específicos para el agente
    "icons": {
        "auth": "fas fa-shield-alt",
        "auth.user": "fas fa-user-shield",       
        "auth.group": "fas fa-users",
        "propiedades.Publicacion": "fas fa-home", 
        "propiedades.ImagenPropiedad": "fas fa-camera", 
        "propiedades.PerfilAgente": "fas fa-user-tie",
        "propiedades.AgenteCorporativo": "fas fa-id-card", # Agregado icono para tu nuevo staff dinámico
    },
    
    # 🌟 AGRUPACIÓN PREMIUM: Esto junta tus modelos bajo menús desplegables prolijos
    "order_with_respect_to": ["propiedades", "propiedades.Publicacion", "propiedades.PerfilAgente", "propiedades.AgenteCorporativo", "propiedades.ImagenPropiedad", "auth"],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-warning",      # Dorado corporativo para botones activos y links
    "navbar": "navbar-dark bg-dark",  # Barra superior negra profunda
    "no_navbar_border": True,         # 🌟 Quitamos bordes duros para suavizar la vista
    "navbar_fixed": True,
    "layout_options": ["navbar-fixed", "sidebar-fixed"],
    "theme": "darkly",                
    "dark_mode_theme": "darkly",
}