# Generated by Django 6.0.6 on 2026-06-16 17:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la publicación')),
                ('descripcion', models.TextField(verbose_name='Descripción o Detalles')),
                ('tipo_propiedad', models.CharField(choices=[('casa', 'Casa'), ('departamento', 'Departamento'), ('monoambiente', 'Monoambiente'), ('ph', 'PH'), ('loft', 'Loft'), ('quinta', 'Casa de Quinta / Barrio Cerrado'), ('terreno', 'Terreno / Lote'), ('cochera', 'Cochera'), ('local', 'Local Comercial'), ('oficina', 'Oficina'), ('galpon', 'Galpón / Depósito'), ('campo', 'Campo / Chacra')], default='departamento', max_length=30, verbose_name='Tipo de Propiedad')),
                ('tipo_operacion', models.CharField(choices=[('alquiler', 'En Alquiler'), ('venta', 'En Venta'), ('alquiler_temporal', 'Alquiler Temporal')], default='venta', max_length=20, verbose_name='Operación')),
                ('moneda', models.CharField(choices=[('USD', 'Dólares (USD)'), ('ARS', 'Pesos (ARS)')], default='USD', max_length=3, verbose_name='Moneda')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
                ('expensas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Expensas (0 si no aplica)')),
                ('ambientes', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ambientes')),
                ('dormitorios', models.PositiveIntegerField(default=0, verbose_name='Dormitorios (0 si es monoambiente)')),
                ('banos', models.PositiveIntegerField(default=1, verbose_name='Baños')),
                ('metros_cubiertos', models.PositiveIntegerField(blank=True, null=True, verbose_name='M² Cubiertos')),
                ('metros_totales', models.PositiveIntegerField(verbose_name='M² Totales')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección (Calle y Altura)')),
                ('barrio_localidad', models.CharField(max_length=100, verbose_name='Barrio o Localidad')),
                ('provincia', models.CharField(default='Buenos Aires', max_length=100, verbose_name='Provincia')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='propiedades/', verbose_name='Foto Principal')),
                ('visitas', models.PositiveIntegerField(default=0, editable=False, verbose_name='Cantidad de Visitas')),
                ('disponible', models.BooleanField(default=True, verbose_name='Publicación Activa / Disponible')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente / Administrador')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-creado_el'],
            },
        ),
        migrations.CreateModel(
            name='ImagenPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='propiedades/galeria/', verbose_name='Foto')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='propiedades.publicacion')),
            ],
            options={
                'verbose_name': 'Foto de la Propiedad',
                'verbose_name_plural': 'Galería de Fotos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='propiedades.publicacion')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
