# Generated by Django 6.0.6 on 2026-06-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='whatsapp_contacto',
            field=models.CharField(default='5491122334455', help_text='Número completo sin espacios ni símbolos. Ejemplo para Argentina: 549116543210', max_length=20, verbose_name='WhatsApp del Agente'),
        ),
    ]
