# Generated by Django 6.0.6 on 2026-06-16 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_publicacion_whatsapp_contacto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='whatsapp_contacto',
        ),
        migrations.CreateModel(
            name='PerfilAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(help_text='Número completo: código de país + código de área sin el 15. Ej: 549116543210', max_length=20, verbose_name='WhatsApp del Agente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Agente',
                'verbose_name_plural': 'Perfiles de Agentes',
            },
        ),
    ]
