# Generated by Django 6.0.6 on 2026-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_remove_publicacion_whatsapp_contacto_perfilagente'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='destacada',
            field=models.BooleanField(default=False, verbose_name='Propiedad Destacada (Sale en la Home)'),
        ),
        migrations.AlterField(
            model_name='perfilagente',
            name='whatsapp',
            field=models.CharField(help_text='Número completo: código de país + área sin el 15. Ej: 549116543210', max_length=20, verbose_name='WhatsApp del Agente'),
        ),
        migrations.DeleteModel(
            name='SolicitudContacto',
        ),
    ]
