# Generated by Django 6.0.6 on 2026-06-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_publicacion_destacada_alter_perfilagente_whatsapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Ilustre')),
                ('email', models.EmailField(max_length=254, verbose_name='Dirección de Email Privada')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono / WhatsApp (Opcional)')),
                ('interes', models.CharField(choices=[('adquisicion', 'Adquisición Residencial Premium'), ('corporativo', 'Búsqueda Corporativa / Comercial'), ('tasacion', 'Tasación de Portafolio')], default='adquisicion', max_length=20, verbose_name='Tipo de Inversión')),
                ('mensaje', models.TextField(verbose_name='Detalles de su Requerimiento Inmobiliario')),
                ('leido', models.BooleanField(default=False, verbose_name='¿Gestionado / Leído?')),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Recepción')),
            ],
            options={
                'verbose_name': 'Consulta de Contacto',
                'verbose_name_plural': 'Consultas de Asuntos Privados',
                'ordering': ['-creado_el'],
            },
        ),
    ]
