# Generated by Django 6.0.6 on 2026-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_consultacontacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteCorporativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo del agente.', max_length=100)),
                ('cargo', models.CharField(choices=[('CEO', 'Founder & CEO'), ('BROKER_SENIOR', 'Senior Private Broker'), ('BROKER_LUXURY', 'Luxury Broker Consultant')], default='BROKER_LUXURY', help_text='Cargo o posición exclusiva en la firma.', max_length=50)),
                ('foto', models.ImageField(help_text='Foto de perfil profesional (recomendado formato vertical).', upload_to='staff/')),
                ('biografia', models.TextField(help_text='Breve reseña sobre su trayectoria y especialidad en el mercado premium.')),
                ('email', models.EmailField(help_text='Correo electrónico de contacto profesional.', max_length=254)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Número para ordenar la aparición en la web (menor número primero).')),
                ('disponible', models.BooleanField(default=True, help_text='Tilda para mostrar u ocultar al agente en la web pública.')),
                ('fecha_incorporacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agente Corporativo',
                'verbose_name_plural': 'Nuestro Staff Exclusivo',
                'ordering': ['orden', 'fecha_incorporacion'],
            },
        ),
    ]
