# Generated by Django 6.0.6 on 2026-06-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_agentecorporativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentecorporativo',
            name='cargo',
            field=models.CharField(choices=[('FOUNDER', 'Founder'), ('CEO', 'Ceo'), ('AGENTE', 'Agente')], default='AGENTE', help_text='Cargo o posición exclusiva en la firma.', max_length=50),
        ),
    ]
