# Generated by Django 6.0.6 on 2026-06-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_alter_agentecorporativo_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='destacada_hero',
            field=models.BooleanField(default=False, verbose_name='Mostrar en el Slider Principal (Hero)'),
        ),
    ]
